### ISSUE TITLE
Missing Day

### ISSUE THREAD

**Issue by AdamPoloha** [mhavey/mhavey.github.io#1]
I don't know if there is any reason, but the 3rd week of advent has no Saturday. Thank you

**Comment by mhavey** [comment]
Adam, you are right. I do not have it in my source data. That mass is missing from my Daily Roman Missal. I will look into this.

**Comment by mhavey** [comment]
Adam, I checked with the folks at Daily Roman Missal. The Saturday of the the third week of Advent always falls between December 17th and December 24th. The masses for these days are special; the weekday masses for these days are specified in the file  https://github.com/mhavey/mhavey.github.io/blob/master/nsmissal/data/masses/advent/4th%2BWeek%2Bof%2BAdvent.json. The mass for this upcoming Saturday (2021-12-18) is mass with title "Dec 18" in this file. 

Here are the readings: 

			"readings": [
				{
					"readingType": "ENTRANCE ANTIPHON",
					"citation": "noref",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/ENTRANCE+ANTIPHON"
				},
				{
					"readingType": "1ST",
					"citation": "Jer 23:5-8",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/1ST"
				},
				{
					"readingType": "PS",
					"citation": "Ps 72:1-2,12-13,18-19 | resp Cf. 7",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/PS"
				},
				{
					"readingType": "GA",
					"citation": "noref",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/GA"
				},
				{
					"readingType": "GOSPEL",
					"citation": "Mt 1:18-25",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/GOSPEL"
				},
				{
					"readingType": "COMMUNION ANTIPHON",
					"citation": "Mt 1:23",
					"uri": "http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18/reading/COMMUNION+ANTIPHON"
				}


It's a little weird, I agree. You can also consult my calendar https://github.com/mhavey/mhavey.github.io/blob/master/nsmissal/data/reports/calendar.csv. In this file, the entry for 2021-12-18 makes it clear that the day's mass is http://jude.org/ns-missal/advent/4th+Week+of+Advent/Dec+18. (You can find that by searching by date: 2021-12-18.)

**Comment by AdamPoloha** [comment]
Thank you very much
